### ISSUE TITLE
Roadmap and How to Get Started Guide

### ISSUE THREAD

**Issue by anjannair** [VueTubeApp/VueTube-Extractor#11]
### Ask your question

Can a roadmap be added and a guide be added too to this project (VueTube Extractor). I want to contribute but don't know how this can be integrated and what is expected.

### Acknowledgements

- [X] I have searched the existing issues and this is a new question, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.
- [X] My question isn't asked in FAQ (Frequently Asked Questions).

**Comment by anjannair** [comment]
Well woops got my answers
