### ISSUE TITLE
VueTube Extractor rewrite checklist

### ISSUE THREAD

**Issue by 404-Program-not-found** [VueTubeApp/VueTube-Extractor#59]
This issue tracks the state of core systems for the extractor rewrite (located in the [youtube-new](https://github.com/VueTubeApp/VueTube-Extractor/tree/master/src/extractors/youtube-new) directory).

## Parser functionalities
Features both planned and implemented are described in the [youtube-new documentation](https://github.com/VueTubeApp/VueTube-Extractor/tree/master/src/extractors/youtube-new/README.md)
- [x] [Optional Properties](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#optional-properties)
- [x] [Default Values](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#default-values)
- [x] [Type Checking](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#type-checking)
- [x] [Strict Mode](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#strict-mode)
- [x] [Sub-Rules](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#sub-rules)
- [x] [Aliases](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#aliases)
- [x] [Sub-rule auto application](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#sub-rules)
- [x] [Key Mapping](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#key-mapping)
- [x] [Result flattening](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#result-flattening)
- [ ] [JSONPath Dot Notation](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#jsonpath-dot-notation)
- [x] [Arrays](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#arrays)
- [x] [Conditional Rule Application](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#conditional-rule-application)
- [x] [Functional Conditions](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#functional-conditions)
- [ ] [Rule Conditions](https://github.com/VueTubeApp/VueTube-Extractor/blob/master/src/extractors/youtube-new/README.md#rule-conditions)

## Requester functionalities
The requester covers any feature that interacts with remote APIs
- [x] Initialising values (API key, context value, visitor data, etc)
- [ ] Retrieve Data from the Home Page (/browse endpoint)
- [ ] Retrieve basic Information of a video (/player endpoint)
- [ ] Retrieve information from the watch page (/next endpoint, ryd API, sponsorblock)
- [ ] Retrieve information from playlists (/browse endpoint)
- [ ] Retrieve information from search (/search endpoint)
- [ ] #60
- [ ] Retrieve information for comment replies (/browse endpoint)
- [ ] Retrieve search suggestions (suggestqueries.google.com) 
- [ ] Send watch information to the youtube server (/api/stats/qoe endpoint)
- [ ] Retrieve information from channels (/browse endpoint)
- [ ] Pagination support for various features (/next endpoint)

## Overall progress
- [ ] Search
- [ ] Search Filters
- [ ] Search Suggestions
- [ ] Home Page
- [ ] Home Page Continuation
- [ ] Video Information
- [ ] Comments
- [ ] Replies
- [ ] Channel Information
